version: "3"

services:
  next-app:
    container_name: next_app
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    networks:
      - website_network

networks:
  website_network:
    external: true