name: Lint and Build

on: 
    push

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          NEXT_TELEMETRY_DISABLED: 1
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                version: 10
            - uses: actions/setup-node@v3
              with:
                node-version: 22
                cache: 'pnpm'
            - run: pnpm install --frozen-lockfile
            - run: pnpm run lint
            - run: pnpm run build