name: Build

on: 
    push

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - run: bun install
    lint:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - run: bun run lint
    build:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - run: bun run build