name: Lint and Build

on: 
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                version: 8
            - uses: actions/setup-node@v3
              with:
                node-version: 20
                cache: 'pnpm'
            - run: pnpm install
            - run: pnpm run lint
            - run: pnpm run build
    deploy:
        runs-on: ubuntu-latest
        environment: prod
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Add SSH key
              env:
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                mkdir -p /home/runner/.ssh
                ssh-keyscan erdragh.dev >> /home/runner/.ssh/known_hosts
                echo "${{secrets.DEPLOY_KEY}}" > /home/runner/.ssh/github_actions
                chmod 600 /home/runner/.ssh/github_actions
            - name: Stop current deployment
              run: ssh -i /home/runner/.ssh/github_actions rocky@erdragh.dev "cd ~/web/erdragh.dev && podman-compose down && rm -r ./*"
              continue-on-error: true
            - name: Deploy
              env:
                GLOBIGNORE: .next:node_modules
              run: scp -r -i /home/runner/.ssh/github_actions . rocky@erdragh.dev:~/web/erdragh.dev/