name: Deploy

on: 
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - uses: actions/checkout@v4
            - name: Add SSH key
              env:
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                mkdir -p /home/runner/.ssh
                ssh-keyscan erdragh.dev >> /home/runner/.ssh/known_hosts
                echo "${{secrets.DEPLOY_KEY}}" > /home/runner/.ssh/github_actions
                chmod 600 /home/runner/.ssh/github_actions
            - name: Stop current deployment
              run: ssh -i /home/runner/.ssh/github_actions rocky@erdragh.dev "cd ~/web/erdragh.dev && podman-compose down && rm -rf ./*"
            - name: Clean deployment
              run: ssh -i /home/runner/.ssh/github_actions rocky@erdragh.dev "podman rm next_app && podman image prune -af"
              continue-on-error: true
            - name: Deploy
              env:
                GLOBIGNORE: .next:node_modules
              run: |
                ls
                echo $(pwd)
                scp -r -i /home/runner/.ssh/github_actions $(pwd)/* rocky@erdragh.dev:~/web/erdragh.dev/
            - name: Start new deployment
              run: ssh -i /home/runner/.ssh/github_actions rocky@erdragh.dev "cd ~/web/erdragh.dev && podman-compose up -d"